<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api } from '../lib/api'
import type { Account, Role } from '../lib/types'
import { useSessionStore } from '../stores/session'
const store = useSessionStore(); const accounts = ref<Account[]>([]); const username = ref(''); const callsign = ref(''); const role = ref<Role>('user'); const password = ref(''); const message = ref('')
async function load() { accounts.value = await api.request('/api/v1/admin/accounts') }
async function create() { try { await api.request('/api/v1/admin/accounts', { method: 'POST', csrf: store.csrf, body: { username: username.value, source_callsign: callsign.value || null, role: role.value, temporary_password: password.value } }); username.value = callsign.value = password.value = ''; await load(); message.value = 'The account was created.' } catch { message.value = 'The account was not created.' } }
async function setDisabled(account: Account) { await api.request(`/api/v1/admin/accounts/${account.id}`, { method: 'PUT', csrf: store.csrf, body: { disabled: !account.disabled } }); await load() }
async function remove(account: Account) { if (confirm(`Delete ${account.username}? This action removes access.`)) { await api.request(`/api/v1/admin/accounts/${account.id}`, { method: 'DELETE', csrf: store.csrf }); await load() } }
onMounted(() => load().catch(() => { message.value = 'Accounts are unavailable.' }))
</script>
<template><div class="space-y-6"><header><h1 class="text-4xl font-black">Accounts</h1><p class="mt-2 text-slate-400">Create accounts and control access.</p></header><p aria-live="polite">{{ message }}</p>
  <section class="surface p-6"><h2 class="text-2xl font-bold">Create account</h2><form class="mt-5 grid gap-4 md:grid-cols-2" @submit.prevent="create"><div><label class="label" for="new-username">Username</label><input id="new-username" v-model="username" class="field" autocomplete="off" required></div><div><label class="label" for="new-callsign">Source callsign</label><input id="new-callsign" v-model="callsign" class="field uppercase" maxlength="10" pattern="[A-Za-z0-9/-]*"></div><div><label class="label" for="new-role">Role</label><select id="new-role" v-model="role" class="field"><option value="user">User</option><option value="admin">Administrator</option></select></div><div><label class="label" for="temp-password">Temporary password</label><input id="temp-password" v-model="password" class="field" type="password" autocomplete="new-password" required></div><div><button class="button-primary" type="submit">Create account</button></div></form></section>
  <section class="surface overflow-x-auto p-6"><h2 class="text-2xl font-bold">Current accounts</h2><table class="mt-4 w-full min-w-[42rem] text-left"><thead><tr class="border-b border-slate-600"><th class="p-3">Username</th><th class="p-3">Role</th><th class="p-3">Callsign</th><th class="p-3">State</th><th class="p-3">Actions</th></tr></thead><tbody><tr v-for="account in accounts" :key="account.id" class="border-b border-slate-800"><td class="p-3 font-bold">{{ account.username }}</td><td class="p-3">{{ account.role }}</td><td class="p-3">{{ account.source_callsign ?? 'Not assigned' }}</td><td class="p-3">{{ account.disabled ? 'Disabled' : 'Enabled' }}</td><td class="flex gap-2 p-3"><button class="button-secondary" type="button" @click="setDisabled(account)">{{ account.disabled ? 'Enable' : 'Disable' }}</button><button class="button-danger" type="button" @click="remove(account)">Delete</button></td></tr></tbody></table></section>
</div></template>
