<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api } from '../lib/api'
import type { Account, Page, Role } from '../lib/types'
import { useSessionStore } from '../stores/session'
import AccountActions from '../components/AccountActions.vue'

const store = useSessionStore()
const accounts = ref<Account[]>([])
const nextCursor = ref<string>()
const username = ref(''); const callsign = ref(''); const role = ref<Role>('user'); const password = ref('')
const adminPassword = ref(''); const resetPassword = ref(''); const editing = ref<Account>(); const busy = ref(false); const message = ref('')

async function load(append = false) { const query = new URLSearchParams({ limit: '50' }); if (append && nextCursor.value) query.set('cursor', nextCursor.value); const page = await api.request<Page<Account>>(`/api/v1/admin/accounts?${query}`); accounts.value = append ? [...accounts.value, ...page.items] : page.items; nextCursor.value = page.next_cursor }
async function proof() { return (await api.request<{ reauth_token: string }>('/api/v1/me/reauth/password', { method: 'POST', csrf: store.csrf, body: { password: adminPassword.value } })).reauth_token }
async function mutate(action: (token: string) => Promise<unknown>, success: string) { busy.value = true; message.value = ''; try { await action(await proof()); await load(); message.value = success; return true } catch { message.value = 'The action failed. Check your password and the account values.'; return false } finally { busy.value = false } }
async function create() { if (await mutate(token => api.request('/api/v1/admin/accounts', { method: 'POST', csrf: store.csrf, reauth: token, body: { username: username.value, source_callsign: callsign.value || null, role: role.value, initial_password: password.value } }), 'The account was created.')) username.value = callsign.value = password.value = '' }
async function save() { if (!editing.value) return; const account = editing.value; if (await mutate(token => api.request(`/api/v1/admin/accounts/${account.id}`, { method: 'PATCH', csrf: store.csrf, reauth: token, body: { username: account.username, source_callsign: account.source_callsign || null, role: account.role, disabled: account.disabled } }), 'The account was updated.')) editing.value = undefined }
async function setDisabled(account: Account) { await mutate(token => api.request(`/api/v1/admin/accounts/${account.id}`, { method: 'PATCH', csrf: store.csrf, reauth: token, body: { disabled: !account.disabled } }), `The account was ${account.disabled ? 'enabled' : 'disabled'}.`) }
async function reset(account: Account) { if (await mutate(token => api.request(`/api/v1/admin/accounts/${account.id}/password`, { method: 'PUT', csrf: store.csrf, reauth: token, body: { password: resetPassword.value } }), 'The temporary password was set. All sessions were revoked.')) resetPassword.value = '' }
async function revoke(account: Account) { await mutate(token => api.request(`/api/v1/admin/accounts/${account.id}/sessions/revoke`, { method: 'POST', csrf: store.csrf, reauth: token, body: {} }), 'All account sessions were revoked.') }
async function clearPasskeys(account: Account) { if (!confirm(`Clear all passkeys for ${account.username} and revoke all sessions?`)) return; await mutate(token => api.request(`/api/v1/admin/accounts/${account.id}/passkeys`, { method: 'DELETE', csrf: store.csrf, reauth: token }), 'All passkeys and sessions were cleared.') }
async function remove(account: Account) { if (!confirm(`Delete ${account.username}? The user will immediately lose access.`)) return; await mutate(token => api.request(`/api/v1/admin/accounts/${account.id}`, { method: 'DELETE', csrf: store.csrf, reauth: token }), 'The account was deleted.') }
onMounted(() => load().catch(() => { message.value = 'Accounts are unavailable.' }))
</script>

<template><div class="space-y-6"><header><h1 class="text-4xl font-black">Accounts</h1><p class="mt-2 text-slate-400">Create accounts and control access.</p></header><p class="min-h-6" aria-live="polite">{{ message }}</p>
  <section class="surface max-w-xl p-6"><h2 class="text-2xl font-bold">Confirm administrator access</h2><label class="label mt-4" for="admin-password">Your current password</label><input id="admin-password" v-model="adminPassword" class="field" type="password" autocomplete="current-password"><p class="mt-2 text-sm text-slate-400">The server consumes a one-use proof for each account change.</p></section>
  <section class="surface p-6"><h2 class="text-2xl font-bold">Create account</h2><form class="mt-5 grid gap-4 md:grid-cols-2" @submit.prevent="create"><div><label class="label" for="new-username">Username</label><input id="new-username" v-model="username" class="field" autocomplete="off" required></div><div><label class="label" for="new-callsign">Source callsign</label><input id="new-callsign" v-model="callsign" class="field uppercase" maxlength="10" pattern="[A-Za-z0-9/-]*"></div><div><label class="label" for="new-role">Role</label><select id="new-role" v-model="role" class="field"><option value="user">User</option><option value="admin">Administrator</option></select></div><div><label class="label" for="initial-password">Initial password</label><input id="initial-password" v-model="password" class="field" type="password" autocomplete="new-password" minlength="15" required></div><div><button class="button-primary" type="submit" :disabled="busy || !adminPassword">Create account</button></div></form></section>
  <section v-if="editing" class="surface border-cyan-500 p-6" aria-labelledby="edit-account-title"><h2 id="edit-account-title" class="text-2xl font-bold">Edit {{ editing.username }}</h2><form class="mt-5 grid gap-4 md:grid-cols-2" @submit.prevent="save"><div><label class="label" for="edit-username">Username</label><input id="edit-username" v-model="editing.username" class="field" required></div><div><label class="label" for="edit-callsign">Source callsign</label><input id="edit-callsign" v-model="editing.source_callsign" class="field uppercase" maxlength="10"></div><div><label class="label" for="edit-role">Role</label><select id="edit-role" v-model="editing.role" class="field"><option value="user">User</option><option value="admin">Administrator</option></select></div><label class="flex min-h-11 items-center gap-2"><input v-model="editing.disabled" type="checkbox" class="size-5">Account disabled</label><div class="flex gap-3"><button class="button-primary" type="submit" :disabled="busy">Save account</button><button class="button-secondary" type="button" @click="editing = undefined">Cancel</button></div></form></section>
  <section class="surface p-6"><h2 class="text-2xl font-bold">Current accounts</h2><div class="mt-4 grid gap-4 lg:hidden"><article v-for="account in accounts" :key="account.id" class="rounded-xl border border-slate-700 p-4" :aria-label="`Account ${account.username}`"><h3 class="text-xl font-bold">{{ account.username }}</h3><dl class="my-4 grid grid-cols-[auto_1fr] gap-x-3 gap-y-2 text-sm"><dt class="text-slate-400">Role</dt><dd>{{ account.role }}</dd><dt class="text-slate-400">Callsign</dt><dd>{{ account.source_callsign ?? 'Not assigned' }}</dd><dt class="text-slate-400">State</dt><dd>{{ account.disabled ? 'Disabled' : 'Enabled' }}</dd></dl><AccountActions :account="account" :busy="busy" :authorized="!!adminPassword" @edit="editing = { ...account }" @toggle="setDisabled(account)" @revoke="revoke(account)" @clear="clearPasskeys(account)" @remove="remove(account)" /></article><p v-if="!accounts.length" class="text-slate-400">No accounts are available.</p></div><div class="mt-4 hidden overflow-x-auto lg:block"><table class="w-full min-w-[58rem] text-left"><thead><tr class="border-b border-slate-600"><th class="p-3">Username</th><th class="p-3">Role</th><th class="p-3">Callsign</th><th class="p-3">State</th><th class="p-3">Actions</th></tr></thead><tbody><tr v-for="account in accounts" :key="account.id" class="border-b border-slate-800"><td class="p-3 font-bold">{{ account.username }}</td><td class="p-3">{{ account.role }}</td><td class="p-3">{{ account.source_callsign ?? 'Not assigned' }}</td><td class="p-3">{{ account.disabled ? 'Disabled' : 'Enabled' }}</td><td class="p-3"><AccountActions :account="account" :busy="busy" :authorized="!!adminPassword" @edit="editing = { ...account }" @toggle="setDisabled(account)" @revoke="revoke(account)" @clear="clearPasskeys(account)" @remove="remove(account)" /></td></tr><tr v-if="!accounts.length"><td class="p-3 text-slate-400" colspan="5">No accounts are available.</td></tr></tbody></table></div>
    <form class="mt-6 flex max-w-xl flex-wrap items-end gap-3" @submit.prevent="editing && reset(editing)"><div class="grow"><label class="label" for="reset-password">Temporary password for selected account</label><input id="reset-password" v-model="resetPassword" class="field" type="password" minlength="15" autocomplete="new-password"></div><button class="button-secondary" type="submit" :disabled="!editing || !resetPassword || busy">Reset password</button></form>
  </section>
  <button v-if="nextCursor" class="button-secondary" type="button" :disabled="busy" @click="load(true)">Load more accounts</button>
</div></template>
