<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue'
import { api, ApiError } from '../lib/api'
import { assertionOptions, registrationOptions, serializeCredential, type CeremonyOptions } from '../lib/passkeys'
import type { Page, Passkey, UserSession } from '../lib/types'
import { useSessionStore } from '../stores/session'

const store = useSessionStore()
const sessions = ref<UserSession[]>([]); const passkeys = ref<Passkey[]>([])
const currentPassword = ref(''); const newPassword = ref(''); const passkeyProof = ref(''); const message = ref(''); const busy = ref(false)
const pendingPasskey = ref<Passkey>(); const confirmRemoveButton = ref<HTMLButtonElement>(); const addPasskeyButton = ref<HTMLButtonElement>(); let removeOrigin: HTMLButtonElement | undefined

async function load() { const [sessionPage, passkeyPage] = await Promise.all([api.request<Page<UserSession>>('/api/v1/me/sessions?limit=50'), api.request<Page<Passkey>>('/api/v1/me/passkeys?limit=50')]); sessions.value = sessionPage.items; passkeys.value = passkeyPage.items }
async function reauthenticate() { if (passkeyProof.value) { const proof = passkeyProof.value; passkeyProof.value = ''; return proof } return (await api.request<{ reauth_token: string }>('/api/v1/me/reauth/password', { method: 'POST', csrf: store.csrf, body: { password: currentPassword.value } })).reauth_token }
async function reauthenticateWithPasskey() { busy.value = true; try { const options = await api.request<CeremonyOptions>('/api/v1/me/reauth/passkey/options', { method: 'POST', csrf: store.csrf, body: {} }); const credential = await navigator.credentials.get(assertionOptions(options)) as PublicKeyCredential | null; if (!credential) throw new Error('No credential'); const result = await api.request<{ reauth_token: string; expires_in_seconds: number }>('/api/v1/me/reauth/passkey/verify', { method: 'POST', csrf: store.csrf, body: { ceremony_id: options.ceremony_id, credential: serializeCredential(credential) } }); passkeyProof.value = result.reauth_token; message.value = 'Passkey confirmation is ready for one sensitive action.' } catch { passkeyProof.value = ''; message.value = 'Passkey confirmation failed.' } finally { busy.value = false } }
async function changePassword() { busy.value = true; try { await api.request('/api/v1/me/password', { method: 'PUT', csrf: store.csrf, reauth: await reauthenticate(), body: { password: newPassword.value } }); message.value = 'Your password changed. Other sessions were revoked.'; currentPassword.value = ''; newPassword.value = ''; await store.refresh() } catch (error) { message.value = error instanceof ApiError && error.code === 'common_password' ? 'Choose a password that is not commonly used.' : error instanceof ApiError && error.code === 'password_context' ? 'Do not include your account, callsign, or service name in the password.' : 'The password did not change.' } finally { busy.value = false } }
async function revoke(id: string) { busy.value = true; try { await api.request(`/api/v1/me/sessions/${encodeURIComponent(id)}`, { method: 'DELETE', csrf: store.csrf, reauth: await reauthenticate() }); await load(); message.value = 'The session was revoked.' } catch { message.value = 'Confirm your identity before you revoke a session.' } finally { busy.value = false } }
function requestPasskeyRemoval(key: Passkey, event: Event) { pendingPasskey.value = key; removeOrigin = event.currentTarget as HTMLButtonElement; void nextTick(() => confirmRemoveButton.value?.focus()) }
function cancelPasskeyRemoval() { pendingPasskey.value = undefined; void nextTick(() => removeOrigin?.focus()) }
async function removePasskey() { const key = pendingPasskey.value; if (!key) return; busy.value = true; try { await api.request(`/api/v1/me/passkeys/${encodeURIComponent(key.id)}`, { method: 'DELETE', csrf: store.csrf, reauth: await reauthenticate() }); pendingPasskey.value = undefined; await load(); message.value = 'The passkey was removed.'; void nextTick(() => addPasskeyButton.value?.focus()) } catch { message.value = 'Confirm your identity before you remove a passkey.'; void nextTick(() => confirmRemoveButton.value?.focus()) } finally { busy.value = false } }
async function enrollPasskey() { busy.value = true; try { const options = await api.request<CeremonyOptions>('/api/v1/me/passkeys/options', { method: 'POST', csrf: store.csrf, reauth: await reauthenticate(), body: {} }); const credential = await navigator.credentials.create(registrationOptions(options)) as PublicKeyCredential | null; if (!credential) throw new Error('No credential'); await api.request('/api/v1/me/passkeys/verify', { method: 'POST', csrf: store.csrf, body: { ceremony_id: options.ceremony_id, name: 'New passkey', credential: serializeCredential(credential) } }); await load(); message.value = 'The passkey was added.' } catch { message.value = 'Confirm your identity, then try to add the passkey again.' } finally { busy.value = false } }
async function renamePasskey(key: Passkey) { busy.value = true; try { await api.request(`/api/v1/me/passkeys/${encodeURIComponent(key.id)}`, { method: 'PATCH', csrf: store.csrf, reauth: await reauthenticate(), body: { name: key.name } }); message.value = 'The passkey name changed.' } catch { message.value = 'The passkey name did not change.' } finally { busy.value = false } }

onMounted(() => { if (!store.session.forced_password_change) load().catch(() => { message.value = 'Security details are unavailable.' }) })
</script>

<template>
  <div class="space-y-6">
    <header><h1 class="text-4xl font-black">Security</h1><p class="mt-2 text-slate-400">Manage your password, passkeys, and signed-in devices.</p></header>
    <section v-if="store.session.forced_password_change" class="surface border-amber-400 p-5" role="alert" aria-labelledby="temporary-password-title"><h2 id="temporary-password-title" class="text-xl font-bold text-amber-200">Change your temporary password</h2><p class="mt-2">Change your temporary password before you use other features.</p><p class="mt-1 text-slate-300">Enter the temporary password as your current password. Then choose a new password with at least 15 characters.</p><a class="button-primary mt-4" href="#new-password">Go to new password</a></section>
    <p class="min-h-6" aria-live="polite">{{ message }}</p>
    <section class="surface p-6"><h2 class="text-2xl font-bold">Confirm your identity</h2><div class="mt-5 grid max-w-lg gap-4"><div><label class="label" for="current-password">Current password</label><input id="current-password" v-model="currentPassword" class="field" type="password" autocomplete="current-password"><p class="mt-1 text-sm text-slate-400">Enter this password before one sensitive action.</p></div><button v-if="store.session.passkey_available && !store.session.forced_password_change" class="button-secondary" type="button" :disabled="busy" @click="reauthenticateWithPasskey">Confirm with a passkey</button></div></section>
    <section class="surface p-6"><h2 class="text-2xl font-bold">Change password</h2><form class="mt-5 max-w-lg space-y-4" @submit.prevent="changePassword"><div><label class="label" for="new-password">New password</label><input id="new-password" v-model="newPassword" class="field" type="password" autocomplete="new-password" minlength="15" required><p class="mt-1 text-sm text-slate-400">Use at least 15 characters.</p></div><button class="button-primary" type="submit" :disabled="busy || (!currentPassword && !passkeyProof)">Change password</button></form></section>
    <template v-if="!store.session.forced_password_change">
      <section class="surface p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold">Passkeys</h2><p class="text-slate-400">Add more than one passkey for reliable access.</p></div><button ref="addPasskeyButton" class="button-primary" type="button" :disabled="busy || !store.session.passkey_available || (!currentPassword && !passkeyProof)" @click="enrollPasskey">Add passkey</button></div><ul class="mt-4 divide-y divide-slate-700"><li v-for="key in passkeys" :key="key.id" class="flex min-h-16 flex-wrap items-end justify-between gap-4 py-3"><div class="grow"><label class="label" :for="`passkey-${key.id}`">Passkey name</label><input :id="`passkey-${key.id}`" v-model="key.name" class="field max-w-sm"><p class="mt-1 text-sm text-slate-400">Added {{ new Date(key.created_at).toLocaleDateString() }}</p></div><div class="flex gap-2"><button class="button-secondary" type="button" :disabled="busy" @click="renamePasskey(key)">Rename</button><button class="button-secondary" type="button" :disabled="busy" :aria-label="`Remove ${key.name}`" @click="requestPasskeyRemoval(key, $event)">Remove</button></div></li><li v-if="!passkeys.length" class="py-4 text-slate-400">No passkeys are enrolled.</li></ul></section>
      <section class="surface p-6"><h2 class="text-2xl font-bold">Sessions</h2><ul class="mt-4 divide-y divide-slate-700"><li v-for="item in sessions" :key="item.id" class="flex min-h-16 items-center justify-between gap-4 py-3"><div><strong>{{ item.current ? 'This device' : 'Signed-in device' }}</strong><p class="text-sm text-slate-400">Last active {{ new Date(item.last_active_at).toLocaleString() }}</p></div><button v-if="!item.current" class="button-secondary" type="button" :disabled="busy" @click="revoke(item.id)">Revoke</button></li><li v-if="!sessions.length" class="py-4 text-slate-400">No session details are available.</li></ul></section>
    </template>
    <div v-if="pendingPasskey" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4" role="alertdialog" aria-modal="true" aria-labelledby="remove-passkey-title" aria-describedby="remove-passkey-description" @keydown.esc="cancelPasskeyRemoval"><section class="surface w-full max-w-md p-6"><h2 id="remove-passkey-title" class="text-2xl font-bold">Remove {{ pendingPasskey.name }}?</h2><p id="remove-passkey-description" class="mt-3 text-slate-300">This passkey cannot be used again. Other enrolled passkeys remain available.</p><div class="mt-5 flex flex-wrap gap-3"><button ref="confirmRemoveButton" class="button-danger" type="button" :disabled="busy" @click="removePasskey">Remove passkey</button><button class="button-secondary" type="button" :disabled="busy" @click="cancelPasskeyRemoval">Cancel</button></div></section></div>
  </div>
</template>
