<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api } from '../lib/api'
import type { Passkey, UserSession } from '../lib/types'
import { useSessionStore } from '../stores/session'
import { registrationOptions, serializeCredential, type CeremonyOptions } from '../lib/passkeys'
const store = useSessionStore(); const sessions = ref<UserSession[]>([]); const passkeys = ref<Passkey[]>([]); const currentPassword = ref(''); const newPassword = ref(''); const message = ref('')
async function load() { [sessions.value, passkeys.value] = await Promise.all([api.request<UserSession[]>('/api/v1/me/sessions'), api.request<Passkey[]>('/api/v1/me/passkeys')]) }
async function reauthenticate() { const result = await api.request<{ reauth_token: string }>('/api/v1/me/reauth/password', { method: 'POST', csrf: store.csrf, body: { password: currentPassword.value } }); return result.reauth_token }
async function changePassword() { try { const proof = await reauthenticate(); await api.request('/api/v1/me/password', { method: 'PUT', csrf: store.csrf, reauth: proof, body: { password: newPassword.value } }); message.value = 'Your password changed. Other sessions were revoked.'; currentPassword.value = ''; newPassword.value = '' } catch { message.value = 'The password did not change.' } }
async function revoke(id: string) { try { const proof = await reauthenticate(); await api.request(`/api/v1/me/sessions/${encodeURIComponent(id)}`, { method: 'DELETE', csrf: store.csrf, reauth: proof }); await load() } catch { message.value = 'Enter your current password before you revoke a session.' } }
async function removePasskey(id: string) { try { const proof = await reauthenticate(); await api.request(`/api/v1/me/passkeys/${encodeURIComponent(id)}`, { method: 'DELETE', csrf: store.csrf, reauth: proof }); await load() } catch { message.value = 'Enter your current password before you remove a passkey.' } }
async function enrollPasskey() { try { const proof = await reauthenticate(); const options = await api.request<CeremonyOptions>('/api/v1/me/passkeys/options', { method: 'POST', csrf: store.csrf, reauth: proof, body: {} }); const credential = await navigator.credentials.create(registrationOptions(options)) as PublicKeyCredential | null; if (!credential) throw new Error('No credential'); await api.request('/api/v1/me/passkeys/verify', { method: 'POST', csrf: store.csrf, body: { ceremony_id: options.ceremony_id, name: 'New passkey', credential: serializeCredential(credential) } }); await load(); message.value = 'The passkey was added.' } catch { message.value = 'Enter your current password, then try to add the passkey again.' } }
onMounted(() => load().catch(() => { message.value = 'Security details are unavailable.' }))
</script>
<template><div class="space-y-6"><header><h1 class="text-4xl font-black">Security</h1><p class="mt-2 text-slate-400">Manage your password, passkeys, and signed-in devices.</p></header><p class="min-h-6" aria-live="polite">{{ message }}</p>
  <section class="surface p-6"><h2 class="text-2xl font-bold">Change password</h2><form class="mt-5 max-w-lg space-y-4" @submit.prevent="changePassword"><div><label class="label" for="current-password">Current password</label><input id="current-password" v-model="currentPassword" class="field" type="password" autocomplete="current-password" required><p class="mt-1 text-sm text-slate-400">Also enter this password before a sensitive security action.</p></div><div><label class="label" for="new-password">New password</label><input id="new-password" v-model="newPassword" class="field" type="password" autocomplete="new-password" minlength="15" required><p class="mt-1 text-sm text-slate-400">Use at least 15 characters.</p></div><button class="button-primary" type="submit">Change password</button></form></section>
  <section class="surface p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-bold">Passkeys</h2><p class="text-slate-400">Add more than one passkey for reliable access.</p></div><button class="button-primary" type="button" :disabled="!store.session.passkey_available" @click="enrollPasskey">Add passkey</button></div><ul class="mt-4 divide-y divide-slate-700"><li v-for="key in passkeys" :key="key.id" class="flex min-h-16 items-center justify-between gap-4 py-3"><div><strong>{{ key.name }}</strong><p class="text-sm text-slate-400">Added {{ new Date(key.created_at).toLocaleDateString() }}</p></div><button class="button-secondary" type="button" @click="removePasskey(key.id)">Remove</button></li></ul></section>
  <section class="surface p-6"><h2 class="text-2xl font-bold">Sessions</h2><ul class="mt-4 divide-y divide-slate-700"><li v-for="item in sessions" :key="item.id" class="flex min-h-16 items-center justify-between gap-4 py-3"><div><strong>{{ item.current ? 'This device' : 'Signed-in device' }}</strong><p class="text-sm text-slate-400">Last active {{ new Date(item.last_active_at).toLocaleString() }}</p></div><button v-if="!item.current" class="button-secondary" type="button" @click="revoke(item.id)">Revoke</button></li></ul></section>
</div></template>
